# Generated by Django 5.0.6 on 2024-06-15 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMoneyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_money', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10)),
                ('quantity', models.BigIntegerField()),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Other', 'Other'), ('Shopping', 'Shopping'), ('Rent', 'Rent'), ('Bills', 'Bills'), ('Salary', 'Salary')], default='Shopping', max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Add Money Info',
                'verbose_name_plural': 'Add Money Info',
                'db_table': 'addmoney',
            },
        ),
    ]
