# Generated by Django 5.0.6 on 2024-06-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmoneyinfo',
            name='description',
            field=models.TextField(default='No description', max_length=100),
            preserve_default=False,
        ),
    ]
