# Generated by Django 5.0.6 on 2024-06-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_addmoneyinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoneyinfo',
            name='Category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Other', 'Other'), ('Shopping', 'Shopping'), ('Rent', 'Rent'), ('Bills', 'Bills'), ('Salary', 'Salary')], default='Shopping', max_length=20),
        ),
    ]
