# Generated by Django 5.0.6 on 2024-06-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_addmoneyinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoneyinfo',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
