# Generated by Django 5.0.6 on 2024-06-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Savings',
            new_name='savings',
        ),
    ]
