name: Deploy to Docker and Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Ensure Python 3.10 is used

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate || venv\Scripts\activate
        pip install -r requirements.txt

    - name: Collect static files
      run: |
        . venv/bin/activate || venv\Scripts\activate
        python manage.py collectstatic --noinput

    - name: Build Docker image
      run: docker build -t kirill7537/rumiexpensetracker:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push kirill7537/rumiexpensetracker:latest

    - name: Log in to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

    - name: Tag and push Docker image to Heroku Container Registry
      run: |
        docker tag kirill7537/rumiexpensetracker:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release the Heroku app
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

    - name: Run makemigrations and migrate on Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku run python manage.py makemigrations --app ${{ secrets.HEROKU_APP_NAME }}
        heroku run python manage.py migrate --app ${{ secrets.HEROKU_APP_NAME }}

    - name: Fetch Heroku logs
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku logs --app ${{ secrets.HEROKU_APP_NAME }} --num 100
